"""lasssstttt

Revision ID: 8d3a61126169
Revises: f3ca3850caf7
Create Date: 2021-08-14 15:16:55.634635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d3a61126169'
down_revision = 'f3ca3850caf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch', sa.Column('user', sa.String(), nullable=True))
    op.drop_constraint('pitch_user_id_fkey', 'pitch', type_='foreignkey')
    op.create_foreign_key(None, 'pitch', 'users', ['user'], ['username'])
    op.drop_column('pitch', 'user_id')
    op.add_column('pitchcomments', sa.Column('user', sa.String(), nullable=True))
    op.drop_constraint('pitchcomments_user_id_fkey', 'pitchcomments', type_='foreignkey')
    op.create_foreign_key(None, 'pitchcomments', 'users', ['user'], ['username'])
    op.drop_column('pitchcomments', 'user_id')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('pitchcomments', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitchcomments', type_='foreignkey')
    op.create_foreign_key('pitchcomments_user_id_fkey', 'pitchcomments', 'users', ['user_id'], ['id'])
    op.drop_column('pitchcomments', 'user')
    op.add_column('pitch', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitch', type_='foreignkey')
    op.create_foreign_key('pitch_user_id_fkey', 'pitch', 'users', ['user_id'], ['id'])
    op.drop_column('pitch', 'user')
    # ### end Alembic commands ###
