"""lasssst

Revision ID: f3ca3850caf7
Revises: 3e771feb952e
Create Date: 2021-08-14 15:07:11.913247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3ca3850caf7'
down_revision = '3e771feb952e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###
